version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run Unittest Suite
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests
            
  deploy_to_render:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger Render Deploy Hook
          command: |
            curl -X POST "$RENDER_DEPLOY_HOOK"

workflows:
  version: 2
  flask_pipeline:
    jobs:
      - build_and_test
      - deploy_to_render:
          requires:
            - build_and_test
          filters:
            branches:
              only: main